version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: preprocess-clean-node-modules
          command: rm -rf node_modules
      - run:
          name: preprocess
          command: yarn
      - run:
          name: test
          command: yarn test
